### ISSUE TITLE
Wrong nodeUri for Polygon

### ISSUE THREAD

**Issue by KatunaNorbert** [oceanprotocol/ocean.js#1010]
Change the `nodeUri` of the Polygon network config inside `configHelperNetworks` to `https://rpc-mainnet.maticvigil.com/`

**Comment by kremalicious** [comment]
it is not wrong, it's just that we are mixing use cases. The `nodeUri` is also used internally by ocean.js for all web3 calls, so also on the `market`. We handle this over there by [selectively adding an infura key to the `nodeUri`](https://github.com/oceanprotocol/market/blob/main/src/utils/ocean.ts#L6-L20), as without it the URL is indeed "wrong".

But think we make use of this already over in https://github.com/oceanprotocol/market/pull/846 but something's not right, or pushing infura URLs does not work with MetaMask, not sure. Regardless, think here in ocean.js we shouldn't change any URLs

**Comment by KatunaNorbert** [comment]
Ah, I see, then it's indeed a wrong use case. The original issue got fixed on the market side so I'm closing this.
