### ISSUE TITLE
try catch clause isn't supposed to match more than single statement

### ISSUE THREAD

**Issue by TimDaub** [oceanprotocol/ocean.js#1152]
see: https://github.com/oceanprotocol/ocean.js/blob/0b50db1d3bf1fa4b7721effe1b6f046732c55409/src/ocean/Assets.ts#L558

The usefulness of a try catch statement, with regard to its capability of matching errors and then addressing them accordingly, comes from matching for one statement many errors.
However, as it's being done in the above example, there are numerous failable statements in a single try catch clause which makes catching particular errors impossible.

**Comment by AnaLoznianu** [comment]
Fixed with: https://github.com/oceanprotocol/ocean.js/pull/1524. 
The refactoring is not merged yet in the main branch as it is still under testing.
