### ISSUE TITLE
ocean.js has criticial security vulnerabilities

### ISSUE THREAD

**Issue by TimDaub** [oceanprotocol/ocean.js#1154]
```
+ @oceanprotocol/lib@0.20.1
added 2620 packages from 1149 contributors, removed 508 packages, updated 2131 packages and audited 4809 packages in 569.533s

243 packages are looking for funding
  run `npm fund` for details

found 187 vulnerabilities (20 low, 102 moderate, 60 high, 5 critical)
```

if you install ocean.js, you'll find that it has critical vulnerabilities. These are not a joke as it could mean that millions of dollars could be stolen in a single attack.

**Comment by kremalicious** [comment]
just like every package importing web3.js or OpenZeppelin contracts. Welcome to the Node.js community.
