### ISSUE TITLE
"Marketplace Flow" README works in v4

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.js#1194]
The v4 version of this flow
https://github.com/oceanprotocol/ocean.js#marketplace-flow

should run end-to-end without errors.

This means updating the README, and if needed, underlying components.

Write the README as integration tests
We can use some of these examples: https://github.com/akshay-ap/Ocean.js-PlayGround/tree/v4

**Comment by jamiehewitt15** [comment]
@AnaLoznianu just to confirm that I'm understanding this correctly. When you say "Write the README as integration tests" does that mean that the integration test is the only outcome of this task? Or do we also want a markdown file that the user can read as a guide?

**Comment by jamiehewitt15** [comment]
How about if I write it as an integration test and then write a bash script that converts it into a markdown file which is easier for the user to read?

**Comment by jamiehewitt15** [comment]
Also, we should think about the steps included in this readme/ guide. Most of this guide is a repetition of the "simple flow". At the moment I'm not really sure what the purpose of this guide is - are we trying to show people how they can use oean.js to create a marketplace? If so, the approach should be entirely different

**Comment by AnaLoznianu** [comment]
The problem with writing everything as a README is that we always have to change it when something changes in the code. And we sometimes forget that and our READMEs don't reflect the actual state anymore.
That's the reason we were thinking to write them as integration tests, with a lot of comments so our users understand what the tests are doing and how can they do their own setup.
 
If we can write also a script to convert the integration test into README files would be just great!

**Comment by AnaLoznianu** [comment]
We have a marketplace flow example in the ocean.py lib: https://github.com/oceanprotocol/ocean.py/blob/v4main/READMEs/marketplace-flow.md

IMO, we should show an example of publishing data NFT and datatoken, consuming, and datapool creation by using the ocean.js lib.

**Comment by jamiehewitt15** [comment]
> If we can write also a script to convert the integration test into README files would be just great!

Yeah, a script to generate a markdown file from the test will be quite straightforward. 

> We have a marketplace flow example in the ocean.py lib

As far as I can tell there is no "simple flow" in ocean.py so it doesn't suffer from duplication in the same way. To some extent, I think we would be better off merging the "simple flow" and "marketplace flow" into one readme guide. I think this readme will largely be the same as the simple flow but with one or two steps added to the end.

**Comment by jamiehewitt15** [comment]
So the simple flow just covers publishing a data NFT & Datatoken? I'm not sure if we need a separate guide for that as it will also be covered in the marketplace flow

**Comment by jamiehewitt15** [comment]
Closed by https://github.com/oceanprotocol/ocean.js/pull/1438
