### ISSUE TITLE
Need add `await` in `CreateExchange()` to prevent create FRE flow from auto complete 

### ISSUE THREAD

**Issue by krisliew** [oceanprotocol/ocean.js#1215]
**Steps to reproduce:**
1) Create Fixed Price 
2) Accept first 2 transaction of `mint` and `create`
3) Wait about 5-10 second here without clicking `Confirm/Reject` on metamask 
![image](https://user-images.githubusercontent.com/39853992/149294276-837a48bd-05a8-465d-ae50-557f8cda0e29.png)
4) and u will see success message 
![image](https://user-images.githubusercontent.com/39853992/149294341-283bef70-1f77-4ed9-8c42-7ed88e5e9474.png)

**Possible Solution:**
Need to add `await` at code below for user to click `Confirm/Reject` on metamask before showing success.
https://github.com/oceanprotocol/ocean.js/blob/2be0918d8355395a4206396d5b592d6cc2d88eab/src/exchange/FixedRateExchange.ts#L149

**Comment by jamiehewitt15** [comment]
Thanks a lot for reporting this @krisliew, I just tested it out and the problem is just like you described. I'll have a look at a possible solution
