### ISSUE TITLE
Change metadataProofs to optional in MetadataAndTokenURI interface

### ISSUE THREAD

**Issue by moritzkirstein** [oceanprotocol/ocean.js#1307]
In reference to https://github.com/oceanprotocol/market/issues/996

In other metadata methods (e.g. [setMetadata](https://github.com/oceanprotocol/ocean.js/blob/aadd1458ba7364a709f6eb94b3f8c123de3c189a/src/tokens/NFT.ts#L1059)) `metadataProofs` is an optional parameter.

When using `setMetadataAndTokenURI` the `metadataAndTokenURI` is using the `MetadataAndTokenURI`interface, where `metadataProofs` [is required](https://github.com/oceanprotocol/ocean.js/blob/aadd1458ba7364a709f6eb94b3f8c123de3c189a/src/%40types/Erc721.ts#L12). To be consistent this should probably also be optional in the interface.

I also noticed some inconsistencies in the naming of parameters. Previously all variable names including `metadata` treat metadata as one word [(e.g. metadataState)](https://github.com/oceanprotocol/ocean.js/blob/aadd1458ba7364a709f6eb94b3f8c123de3c189a/src/tokens/NFT.ts#L1053). In the interface, `metaData` is now written in camelcase, for example: [metaDataState](https://github.com/oceanprotocol/ocean.js/blob/aadd1458ba7364a709f6eb94b3f8c123de3c189a/src/%40types/Erc721.ts#L4)

**Comment by mihaisc** [comment]
Good points, it should be `metadata` because it's one word.
