### ISSUE TITLE
As an NFT Owner, I am not able to call `setPaymentCollector` due to the condition checking here

### ISSUE THREAD

**Issue by krisliew** [oceanprotocol/ocean.js#1341]
**Issue:**
As an NFT Owner, I am not able to call `setPaymentCollector()` due to the condition checking here

https://github.com/oceanprotocol/ocean.js/blob/d8a7d42a9e75cb36edf47381a29d4418ee7bc249/src/tokens/Datatoken.ts#L788-L790

**Impact:**
- Owner need to set himself as a `paymentManager` first in Ocean.js before able to call `setPaymentCollector()`. 

**Expectation:**
- I should be able to call `setPaymentCollector()` as an `Owner` according to the smart contract:
https://github.com/oceanprotocol/contracts/blob/249c9b2d51c79a95dce5f427e33a1a648c4d8576/contracts/templates/ERC20TemplateEnterprise.sol#L696-L701

**Possible Solution:**
- Add a  `||` OR condition checking to see if the `address` caller is not the `owner`, then throw similar error as in the smart contract: `Caller is not Fee Manager or Owner` 
- Hence, `Owner` will be able to call `setPaymentCollector()` from Ocean.js

**Comment by soonhuat** [comment]
this issue should be not valid any, since during publish there a parameter to directly set paymentCollector

**Comment by mihaisc** [comment]
So we can close this?

**Comment by soonhuat** [comment]
> So we can close this?

I just recheck the condition in smart contract, previously, i was wrong, and i think we still need this issue
Maybe I could create a short PR later, just to make the access checking condition same as smart contract access checking condition
