### ISSUE TITLE
READMEs as integration tests

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/ocean.js#1354]

**Comment by AnaLoznianu** [comment]
Related ocean.py issue: https://github.com/oceanprotocol/ocean.py/issues/743

**Comment by jamiehewitt15** [comment]
My proposal is to simplify all of our documentation to just two files: the `readme.md` and a `codeExamples.md` file which will be auto-generated from an integration test.

- The readme can be for a general introduction and simple instructions on how to install and import the library. It should not contain any code examples.
- The codeExamples integration test should cover all of our main use cases:
  - [ ] Publishing a fixed price asset
  - [ ] Publishing an asset with a pool
  - [ ] Publishing an asset with free pricing 
  - [ ] Consuming each of those assets
  - [ ] Adding liquidity to a pool
  - [ ] Swapping Ocean tokens for a datatoken
- The `codeExamples.test.ts` file will be converted into markdown with a bash script
- The current docs folder and all of its content will be deleted.

**Comment by AnaLoznianu** [comment]
@jamiehewitt15 I like this approach!  Please keep in mind that even though right now we don't have a C2D readme, we need to have examples of this functionality as well

**Comment by jamiehewitt15** [comment]
Yeah, maybe it will make sense to put the compute to data examples in a separate file. That's a reasonable place to introduce some separation
