### ISSUE TITLE
Gas limit estimated incorrect when editing price aka `setRate()`

### ISSUE THREAD

**Issue by krisliew** [oceanprotocol/ocean.js#1443]
**Describe the bug**
- The gas limit estimated for `setRate()` seems to be not working as the gas limit submitted on chain is higher than it should be of `1,000,001`. 

**To Reproduce**
1. Go to https://v4.market.oceanprotocol.com/publish/1 and publish a fixed priced asset
2. After publishing, go to the asset page and click on `Edit` and update the price of the asset
![image](https://user-images.githubusercontent.com/39853992/165436656-fec4c574-a350-4714-97b7-6169a76401b3.png)
3. Check the `setRate()` transaction on etherscan or metamask for the `Gas Limit` and `Gas Used` after transaction status is confirmed
- Gas limit of `1,000,001` : 
![image](https://user-images.githubusercontent.com/39853992/165436699-003dfd5c-c802-4abd-96bc-03c86b7b1ce6.png)
https://rinkeby.etherscan.io/tx/0x9b22a1097416e14204baa07b2eb228539a6d40755f026b35dadde53ced2ce908
![image](https://user-images.githubusercontent.com/39853992/165436197-866c898e-8a8a-468b-af91-8ac13e708ad4.png)

**Expected behavior**
- Gas limit estimation should be lower than `1,000,001` for better gas estimation.
- Example of better gas estimation from Calling `9. setRate` from [etherscan **Write Contract** tab](https://rinkeby.etherscan.io/address/0x30c180860001355e6c6739c97f76a7207e0ac272#writeContract): https://rinkeby.etherscan.io/tx/0xadc91eb4c05de26e12e5c2802574b7d2beca61be05cba312f8ef397aef156744
![image](https://user-images.githubusercontent.com/39853992/165438696-0b424002-ccfd-40b7-a868-db4cde9b59c5.png)

**Possible future impact**
- Estimated transaction fee to user in future production network (e.g. ethereum mainnet) will be very high comparing to actual which might "scare" the user away before they execute it
- User with lower balance of the network native currency might not be able to execute the transaction with the high gas limit estimated.

**Comment by jamiehewitt15** [comment]
Actually, all of the gas estimates in `src/pools/fixedRate/FixedRateExchange.ts` are 1000000

**Comment by mihaisc** [comment]
that means all of them fail 👍

**Comment by jamiehewitt15** [comment]
> that means all of them fail +1

Yeah exactly
