### ISSUE TITLE
Investigate container checksum issues

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean.js#1459]
There is a mismatch between market (trustedAlgorithm.containerSectionChecksum) and the provider computed checksum.

`ocean_provider.routes.compute - ERROR - containerSectionChecksum for algorithm with did did:op:3165c87fc93f574afc2a993f4327a4433baeefbecb12ff9f9c799d8e63c7c3dc does not match`

Possible problems:

- there is space for json.dumps after every `:`
- there is another space for json.dumps after every `,`
- previously checksum attribute were at last (4th position within the object), now is at first (1st position)

we previously solved the order issue in the market here :->  https://github.com/oceanprotocol/market/blob/feature/v4-c2d/src/@utils/compute.ts#L334

**Comment by mihaisc** [comment]
It's kinda hard to enforce that order (from the market). Maybe we should have a function in ocean.js/py that does that hash and we can enforce that order. Or think of a way so that the order is not relevat.

**Comment by AnaLoznianu** [comment]
This issue will be fixed with file checksum changes that are in progress. closing it as it's old and we did many changes since this was created
