### ISSUE TITLE
Discrepancy between docs and CLI output

### ISSUE THREAD

**Issue by domingosl** [oceanprotocol/ocean.js#1491]
In the documentation [Beginners guide](https://github.com/oceanprotocol/ocean.js/blob/v4main/docs/beginners_guide.md) it said that the values contained in the config file:

```
const contracts = {
 "DTFactory": "0x_YOUR_DTFactory_ADDRESS_",
 "BFactory": "0x_YOUR_DTFactory_ADDRESS_",
 "FixedRateExchange": "0x_YOUR_DTFactory_ADDRESS_",
 "Metadata": "0x_YOUR_Metadata_ADDRESS_",
 "Ocean": "0x_YOUR_Ocean_ADDRESS_"
}; 
```

Should be replaced by the output of the command `cat ~/.ocean/ocean-contracts/artifacts/address.json` run on the host machine. According to the docs, the expected output is:

```
{
 "development": {
   "DTFactory": "0x27F7b0C827596C7355ee39EdFd3235F8b47C2862",
   "BFactory": "0xCe7c408C56f8BFF8EF616F5CE3E7868486de3748",
   "FixedRateExchange": "0xf4C7B100cECA95Badc583bdBd10F6CA8D9123B09",
   "Metadata": "0x2c11A9763AaCb838fDFD6Ee01fD1179196ee20f5",
   "Ocean": "0x11570aE63B4fDe21d213Bc1A9BF61eEA51d13D56"
 }
}
```

But actually, the output is way longer and with keys that do not match what's required in config:

![image (1)](https://user-images.githubusercontent.com/2782026/171404900-4efdad17-8659-46b2-8abb-5860a1312ddd.png)

Is this an old outdated doc or am I just being dumb?

**Comment by jamiehewitt15** [comment]
The beginners guide has been deprecated as it relates to Ocean V3. It was replaced by the code examples documentation
