### ISSUE TITLE
Support headers in UrlFile

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/ocean.js#1530]
As per the provider issue, the change was to add headers support on the Fileinfo endpoint

Provider issue: https://github.com/oceanprotocol/provider/issues/504
Ocean.py issue: https://github.com/oceanprotocol/ocean.py/pull/870

**Comment by EnzoVezzaro** [comment]
Market's waiting for this changes to be made. Also, according to #1554 [comment](https://github.com/oceanprotocol/market/issues/1554#issuecomment-1315163327) we need to make sure graphql has also support for headers.

@AnaLoznianu Can you please assign this please, I though I was already handle on ocean.js

**Comment by bogdanfazakas** [comment]
closed by #1665
