### ISSUE TITLE
`No ARWEAVE_GATEWAY defined` error when using Arweave as provider type

### ISSUE THREAD

**Issue by EnzoVezzaro** [oceanprotocol/ocean.js#1641]
**Describe the bug**  ``
When trying to call `getFileInfo` with Arweave we get the following error:
`No ARWEAVE_GATEWAY defined, can not resolve arweave transaction id.`

Network response:
<img width="723" alt="Screenshot 2022-10-27 at 08 07 43" src="https://user-images.githubusercontent.com/13741335/198280788-949bc61a-cc0d-4dd4-87c6-cdf9bf58142f.png">

Payload:

`{
    "type": "arweave",
    "transactionId": "qDGiE4q1N3m5w_zkr4Np1OLW4iS9A79j3GcyVomp0ZM"
}`

**Comment by mihaisc** [comment]
Is this error from ocean.js or from provider? Why would you need a gateway in ocean.js?

**Comment by mihaisc** [comment]
so it's a provider issue 😄  , please move it there
