### ISSUE TITLE
For gtc hackathon (and generally), write short readme on ocean.js for ERC725 / SBTs

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.js#1668]
### Background / Motivation

Gitcoin is hosting hackathon on building blocks for Sybil protection. They've asked Ocean to be involved. Andrea A has been iterating with them.

Andrea A, Ana, Jaime and Trent had a call to discuss how Ocean can put its best foot forward, towards people building tools for Sybil protection.

We arrived at three things. Starting with the highest-USP item for this use case:
1. ocean.js interface to data NFTs with ERC725 to implement Soul Bound Tokens (SBTs) and more.
2. ocean.py ""
3. publish sybil protection algorithms via Ocean Market

At a higher level, for the hackathon, Andrea A will handle all of these. _This_ issue focuses on item (1).

Why SBTs: 
- because they're a highly useful building block for various Sybil protection approaches. 
- And, more generally, ERC725 is a highly useful building block. Ocean has a first-class implementation of it, deployed on many networks, and with drivers.

Why ocean.js: 
- Looking at past Gitcoin competitions, the developers tend to be dapp developers, therefore devs who know JS and Solidity. 

Bonus:
- It's useful to show people how to use ERC725 / SBTs in ocean.js anyway, outside the competition. 

ocean.py ERC725 examples:
1. [Key-value database](https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/key-value-flow.md) - use data NFTs to store arbitrary key-value pairs on-chain, following ERC725
2. [Profile NFTs](https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/profile-nfts-flow.md) - enable "login with Web3" where Dapp can access private user profile data

### TODO for this issue

Implement in ocean.js, a README similar to ocean.py [Key-value database](https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/key-value-flow.md).

(Or perhaps, put it as a linkable section in ocean.js's [CodeExamples.md](https://github.com/oceanprotocol/ocean.js/blob/main/CodeExamples.md).)

**Comment by trentmc** [comment]
@AnaLoznianu , off to you!

**Comment by AnaLoznianu** [comment]
ERC725 in ocean.js functions:
* https://github.com/oceanprotocol/ocean.js/blob/main/src/contracts/NFT.ts#L756
* https://github.com/oceanprotocol/ocean.js/blob/main/src/contracts/NFT.ts#L796

This could be helpful as well: 
* Changing the ownership and the permissions: https://github.com/oceanprotocol/ocean.js/blob/main/src/contracts/NFT.ts#L321-L399

**Comment by AnaLoznianu** [comment]
Thank you @jamiehewitt15 for taking care of this so fast 🙏
