### ISSUE TITLE
Transactions on Mumbai & Polygon should be min = 30gwei

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/ocean.js#1670]
Our users reported that they are getting the "Transaction underpriced error" on Mumbai: https://discord.com/channels/612953348487905282/720631837122363412/1052546895060410418

We need to make sure we increase the gas for Mumbai to at least 30gwei 

Additional info: 
- [ ] https://community.infura.io/t/polygon-mumbai-testnet-error-transaction-underpriced/4781/5
- [ ] https://thecoin.news/articles/polygon-matic-raise-gas-fee-gwei-prevent-spam-transactions-1633594027449

**Comment by mihaisc** [comment]
we need to add an if here https://github.com/oceanprotocol/ocean.js/blob/94fd276d6b34b3e4d620871d06e7e23271be6868/src/utils/ContractUtils.ts#L84

**Comment by alexcos20** [comment]
https://thecoin.news/articles/polygon-matic-raise-gas-fee-gwei-prevent-spam-transactions-1633594027449
