### ISSUE TITLE
Add a type declaration file

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/ocean.js#1850]
If you try and use ocean.js from another typescript project in strict mode, you will get this error: 

```
Could not find a declaration file for module '@oceanprotocol/lib'. '/home/jamie/Desktop/ocean/vscode-extension/node_modules/@oceanprotocol/lib/dist/lib.js' implicitly has an 'any' type.

Try `npm i --save-dev @types/oceanprotocol__lib` if it exists or add a new declaration (.d.ts) file containing `declare module '@oceanprotocol/lib';`ts(7016)
```

We don't have a type declaration file so there there is no easy way round this for developers.

**Comment by alexcos20** [comment]
current version:

![image](https://github.com/user-attachments/assets/ac032cd4-5221-4d1e-86ed-289c2cdf1ac5)

old version:

![image](https://github.com/user-attachments/assets/27ddf04e-7b4f-42a1-9f5b-2503a66e085f)


But not sure that src/types/...  is the correct path

**Comment by jamiehewitt15** [comment]
I think it's just a simple error. In package.json we have ` "types": "./dist/src/index.d.ts",` but the actual file name is `index.ts`
