### ISSUE TITLE
New build process

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/ocean.js#246]
Currently `tsc` is used to output only one big CommonJS ES5 file. This works but prevents projects using the library to do their own optimizations like tree shaking during their build process, creating a huge lib-js dependency file. To solve that we need multiple outputs:

- CommonJS module
- ES module
- UMD

Over on `react` we use [`microbundle`](https://github.com/developit/microbundle) to achieve that with minimal config.

Should also produce a file usable via unpkg.com

**Comment by kremalicious** [comment]
In production, ocean.js bundle size minified is 6MB!

**Comment by jamiehewitt15** [comment]
@kremalicious Do you suggest using microbundle for ocean.js as well or is there any reason why it wouldn't work?

**Comment by jamiehewitt15** [comment]
I have implemented this with `microbundle` here: https://github.com/oceanprotocol/ocean.js/pull/698

**Comment by kremalicious** [comment]
nice, yes, this would have been my first suggestion too, use `microbundle` and see what happens :-)
