### ISSUE TITLE
update examples for real implemented flows

### ISSUE THREAD

**Issue by nazariyv** [oceanprotocol/ocean.js#279]
https://github.com/oceanprotocol/ocean-lib-js/blob/main/docs/quickstart_marketplace.md

the top paths

```
import { TestContractHandler } from '../TestContractHandler'
import { DataTokens } from '../../src/datatokens/Datatokens'
import { Ocean } from '../../src/ocean/Ocean'
```

'../' is what? what directory are we in. Isn't this an example I can just run in my own repo somewhere?

**Comment by trentmc** [comment]
Obsolete, as far as I can tell.

Reopen if you see otherwise.
