### ISSUE TITLE
FixedPriceExchange BuyDT MetaMask error on Rinkeby

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/ocean.js#284]
When I buy a token from a fixed price exchange MetaMask throws the following error in the browser console. All the flow is working ok: I buy the dt, order asset, download asset. So basically the only issue is that there is an unknown error in the console and someone may notice is and think that something broke. This is a minor issue.

![image](https://user-images.githubusercontent.com/26000280/93313403-1b0a1700-f811-11ea-93b7-1a627cceaed9.png)

**Comment by marcojrfurtado** [comment]
I am getting this pretty consistently on Rinkeby for larger transactions
