### ISSUE TITLE
Change the naming of DDO to metadata

### ISSUE THREAD

**Issue by 0x3bfc** [oceanprotocol/ocean.js#366]
https://github.com/oceanprotocol/ocean.js/blob/7d15d2d1d98005bed73204bab22567953ef5746e/src/metadatacache/OnChainMetaDataCache.ts#L1

**Comment by trentmc** [comment]
I believe we discussed this about 6 weeks ago and agreed not to do it. Partly because of the implications (as Alex mentioned) and also because "DDO" is more precise.
