### ISSUE TITLE
Increase maintainability score & code coverage on CodeClimate

### ISSUE THREAD

**Issue by 0x3bfc** [oceanprotocol/ocean.js#374]
Based on the generated report by codeclimate, more details to be found [here](https://codeclimate.com/repos/5f871c2c87b6045061001233/issues?category=duplication&engine_name%5B%5D=structure&engine_name%5B%5D=duplication)

Bring code base to:

- Maintainability: A
- Coverage >80%

**Comment by kremalicious** [comment]
Worth noting that CodeClimate estimates 3 weeks of full-time 1-person work to solve all issues for Maintenance score:

<img width="1015" alt="Screen Shot 2021-03-03 at 02 31 57" src="https://user-images.githubusercontent.com/90316/109738745-a5c8ad80-7bc8-11eb-9bae-f491e36f917d.png">

**Comment by kremalicious** [comment]
If we start fresh, we will start with all in the green from the start
