### ISSUE TITLE
SubscribablePromise tests throw errors

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/ocean.js#397]
Seen e.g. in https://travis-ci.com/github/oceanprotocol/ocean.js/jobs/403624636#L1645, the unit tests for it show errors but the tests still succeed. But they will fail with Node.js v15 so we should investigate what's going on in those tests to make them run without throwing errors.

**Comment by bogdanfazakas** [comment]
could not reproduce the issue, run the SubscribablePromise unit test locally with the latest version (v15.7.0) of node.js available for macOS installed, also the error is no longer displayed in the travis ci

**Comment by kremalicious** [comment]
perfect, bugs which solve themselves. Thanks for checking that!
