### ISSUE TITLE
update SearchQuery typings for new nativeSearch

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/ocean.js#453]
See:
- https://github.com/oceanprotocol/market/blob/35ec06b75c898585a6bd3e5edf84cd1133b20450/src/components/pages/Home.tsx#L23-L57
- https://github.com/oceanprotocol/market/blob/08965070972b35b34cbf9c837b3dde90128c7fdc/src/components/templates/Search/utils.ts#L18-L35

**Comment by alexcos20** [comment]
Deprecate custom search (use native query) and close this

**Comment by kremalicious** [comment]
done as part of #662
