### ISSUE TITLE
Issue with ocean.js marketplace quickstart 

### ISSUE THREAD

**Issue by AmanRaj1608** [oceanprotocol/ocean.js#517]
In the [Quickstart: Marketplace Flow](https://github.com/oceanprotocol/ocean.js/blob/HEAD/docs/quickstart_marketplace.md#2-alice-publishes-assets-for-data-services--publishes-a-datatoken-contract) code
```ts
const alice = (await ocean.accounts.list())[0]

datatoken = new DataTokens(
  config.factoryAddress,
  factory.abi,
  datatokensTemplate.abi,
  web3
)
```
While creating DataTokens it says 
Error - `Expected 5 arguments, but got 4.ts(2554)`
As we need to pass the Logger too

![image](https://user-images.githubusercontent.com/42104907/103445947-05294080-4ca0-11eb-81e0-95ef7534f956.png)

**Comment by alexcos20** [comment]
you need to instantiate your own instance of logger class
