### ISSUE TITLE
Ocean.js: Secure algorithms

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean.js#572]
change the structure of trustedAlgorithms in the ddo from :
trustedAlgorithms=['DID1','DID2']
to
```json 
publisherTrustedAlgorithms=
{
"did1":{
"filesChecksum":"1234",
"containerSectionChecksum":"7676"
},
"did2":{
"filesChecksum":"1232334",
"containerSectionChecksum":"98787"
}
}
```
where:
`filesChecksum = sha256 (file_content_checksum_URL0+file_content_checksum_URL1+..)`
and `containerChecksum = sha256(ddo_container_section_as_json)`

**Comment by 0x3bfc** [comment]
I recommend to rename the issue to `publisher's trusted algorithms` as @trentmc mentioned yesterday. `secure algorithms` implies different meaning :)

**Comment by kremalicious** [comment]
data structure: shouldn't this be an array? And using DIDs as object keys is often problematic. So how about:

```js
const publisherTrustedAlgorithms = [
  {
    "did": "0xxxxx"
    "filesChecksum":"1234",
    "containerSectionChecksum":"7676"
  },
    "did": "0xxxxx"
    "filesChecksum":"1232334",
    "containerSectionChecksum":"98787"
  }
]
```

**Comment by alexcos20** [comment]
agreed
