### ISSUE TITLE
Error 500 when starting a compute job

### ISSUE THREAD

**Issue by TSS-LauKY** [oceanprotocol/ocean.js#583]
**Describe the bug**
Error 500 when starting a compute job using ocean.compute.start() function.

**To Reproduce**
Code structure follow the example
https://github.com/oceanprotocol/ocean.js/blob/feature/example/example/src/commands.ts#L213

**Value of the function**
start(
'did:op:aB17c494EA9954CBa9C6F7D3C445c890E56eb001', 
'0xd88e04dc9cfd637b9c72233a4aa7b6f748d6784f3fbb851c3718bdc6e2d1ad29', 
'0xaB17c494EA9954CBa9C6F7D3C445c890E56eb001', 
consumerAccount: [Account Object], 
'did:op:6004D9FcA374E84Ad60EDeAba8A83ac43038F6Ed', 
null, 
null, 
'1', 
'compute', 
'0x672a7195173161d335b885422b7694d3af42fdb4085a21e65d36bd1ae7050ca5', 
'0x6004D9FcA374E84Ad60EDeAba8A83ac43038F6Ed'
)

Error:
![image](https://user-images.githubusercontent.com/71874741/106854993-3493f880-66f7-11eb-8e0a-b19a26e8d503.png)

![image](https://user-images.githubusercontent.com/71874741/106855103-5db48900-66f7-11eb-89e2-cf107ff57e00.png)

POST | https://provider.data-marketplace.io/api/v1/services/compute?documentId=did:op:aB17c494EA9954CBa9C6F7D3C445c890E56eb001&signature=0x2500363f962c021940f6cc16c0dcadc984cba1edd29d029052f16f51ccc8da7b6259dd9c58dd67d493a0a28d4435394d0dc08621533ec3ab7d41813f3c3935d41c&output={"publishAlgorithmLog":false,"publishOutput":false}&algorithmDid=did:op:6004D9FcA374E84Ad60EDeAba8A83ac43038F6Ed&consumerAddress=0x1aEF750253B4954B42C980D99856d32474B2C3db,0x1aEF750253B4954B42C980D99856d32474B2C3db&transferTxId=0xd88e04dc9cfd637b9c72233a4aa7b6f748d6784f3fbb851c3718bdc6e2d1ad29&algorithmTransferTxId=0x672a7195173161d335b885422b7694d3af42fdb4085a21e65d36bd1ae7050ca5&algorithmDataToken=0x6004D9FcA374E84Ad60EDeAba8A83ac43038F6Ed&serviceId=1&serviceType=compute&dataToken=0xaB17c494EA9954CBa9C6F7D3C445c890E56eb001

**Comment by kremalicious** [comment]
the linked example folder and code is a draft not meant for production. We do not support Compute-to-data in its full flow right now and there are so many untested moving parts with it outside of ocean.js so that it would be hard to investigate anything related to this issue here. So closing for now until we officially support Compute-to-data together with v3 components
