### ISSUE TITLE
deprecation of web3-shh & web3-bzz

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/ocean.js#586]
web3.js says:

```
web3-shh package will be deprecated in version 1.3.5 and will no longer be supported.
web3-bzz package will be deprecated in version 1.3.5 and will no longer be supported.
```

We need to check how we use that and if we need to replace it with something else.

**Comment by trentmc** [comment]
https://travis-ci.com/github/oceanprotocol/ocean.js/builds/220071023

**Comment by jamiehewitt15** [comment]
As far as I can tell, we aren't using `web3-shh` or `web3-bzz`anywhere in ocean.js. These warnings print to the console whenever web3 is Instantiated regardless of whether we are using them. There is a similar issue raised about this in the web3.js repo: https://github.com/ChainSafe/web3.js/issues/3898

I can look into seeing if we can suppress these warnings in the output.

**Comment by kremalicious** [comment]
awesome, thanks for investigating. Think we're good then, as long as we do not access `web3.shh` or `web3.bzz` in our code we should be safe for that deprecation in the next web3.js bump

**Comment by jamiehewitt15** [comment]
ok cool

**Comment by trentmc** [comment]
Fastest first issue ever, congrats Jamie:) 

Maybe trivial, but I _love_ simple and trivial!

**Comment by jamiehewitt15** [comment]
Thanks a lot @trentmc
