### ISSUE TITLE
Token get deducted but not able to download a file

### ISSUE THREAD

**Issue by TSS-LauKY** [oceanprotocol/ocean.js#597]
**Describe the bug**
Token get deducted but not able to download a file

**To Reproduce**
Consume a problematic asset, example invalid provider URL

**Expected behavior**
Check on the provider endpoint is valid before data token exchange during make order

**Additional context**
Example asset:
https://market.oceanprotocol.com/asset/did:op:1aFd29f088baE005fC4B00D8066358b2ceD0683a

**Comment by alexcos20** [comment]
Data Token is not transferred from your wallet if the asset is not available.

Can you double check and confirm ?

**Comment by srikanthkaja31** [comment]
@alexcos20 Yes tokens got deducted.

**Comment by alexcos20** [comment]
I just added a integration test for this:  https://github.com/oceanprotocol/ocean.js/pull/630/commits/5e7c6cb497c34bc1f4d750a876aa9b0848b1e8b6
and it passes.

what version of the provider are you running?
Can you paste the transaction logs ?

**Comment by TSS-LauKY** [comment]
Transaction:
https://rinkeby.etherscan.io/tx/0x5b4c1ee3d0e1b44adc6003bd1870be6d60b5e16b16e56696a41da83b0d11a23e

Error in the console:
![image](https://user-images.githubusercontent.com/71874741/108982403-bceb3500-76c8-11eb-932f-5801282d9082.png)
