### ISSUE TITLE
Integration tests are failing on main

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/ocean.js#628]
For whatever reason, test runs on `main` are still broken despite them being successful as PRs. This is all after the recent provider/barge changes and after #612 was introduced.

Likewise, all new PRs have a broken branch build while their PR build succeeds. All of them fail at the same thing, updating metadata. This might imply some test problem where multiple test runs write to the same Docker images in barge

https://travis-ci.com/github/oceanprotocol/ocean.js/builds/217973538#L1902

**Comment by alexcos20** [comment]
All of them are related to provider.  Check this:  https://github.com/oceanprotocol/provider/issues/101

source of logs:  https://travis-ci.com/github/oceanprotocol/ocean.js/builds/217829800#L714

**Comment by kremalicious** [comment]
ocean.py shows the same behavior implying this has something to do with provider in barge https://github.com/oceanprotocol/ocean.py/pull/134

**Comment by kremalicious** [comment]
solved by https://github.com/oceanprotocol/barge/pull/231
