### ISSUE TITLE
EstimateGas functions for all functions that are sending transactions on chain

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean.js#676]
Right now, we are using internal estimateGas functions, like:
https://github.com/oceanprotocol/ocean.js/blob/main/src/balancer/Pool.ts#L74-L89

We need to move this estimation out of this functions and have something like:

function estimateGasSetup(...) which will return the following :
 - totalGas  - total gas used by transaction (in wei)
 - gasPrice -  optimal gas price
 - totalCost -  (totalGas * gasPrice) - in number, converted from Wei

and setup(..) will use estimateGasSetup(..) instead of having the estimate in the function body

By this, market will be able to show an estimated cost of the transaction before the user clicks submit

Classes affected:
 - pool
 - datatokens
 - fixedRateExchange
 - ....

Bonus: Resolve code duplication as well

**Comment by alexcos20** [comment]
ps: do not start working at #676 and #677 in the same time, you will have a hard time merging the two branches

**Comment by kremalicious** [comment]
Not in scope for new ocean.js or market for v4 so closing.
