### ISSUE TITLE
EIP-155

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean.js#677]
With Geth v1.10.0, EIP-155 is enforced (see https://blog.ethereum.org/2021/03/03/geth-v1-10-0/, chapter "ChainID enforcement")

All transactions need to follow https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md or they will be rejected in the future (Infura runs v1.10.0, but with --rpc.allow-unprotected-txs, so we are safe for the moment ).

All sending transactions should include chainId as well.

(Tested ocean.js with a rinkeby synced geth v1.10.0, and all transactions are failing with   "only replay-protected (EIP-155) transactions allowed over RPC")

**Comment by alexcos20** [comment]
ps: do not start working at #676 and #677 in the same time, you will have a hard time merging the two branches

**Comment by trentmc** [comment]
Note, based on AlexC comments: put to high priority because the current workaround is Infura, and they might stop support for this at any minute. Ideally by Apr 7 or so.

**Comment by bogdanfazakas** [comment]
Tested against a synced Ropsten node with enforced EIP-155, and with the latest web3 library installed all transactions seemed fine, no need to manually add the chainId
