### ISSUE TITLE
Move from node-fetch to cross-fetch

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean.js#678]
**Describe the bug**
Some of the methods exposed by node-fetch are not available in browser (most important, response.buffer())

Let's investigate if we can mitigate this by using cross-fetch (https://github.com/lquixada/cross-fetch)

**Comment by jamiehewitt15** [comment]
Cross fetch looks like a good option for this, it is recommended by node-fetch for isomorphic usage. It also seems to be the most popular cross platform option. 

One question about this though, we are currently importing types from `node-fetch` (`BodyInit, RequestInit, Response`) and `cross-fetch` doesn't provide any types. Do we want to continue importing the types from `node-fetch` or shall we define them ourselves?
