### ISSUE TITLE
Normalize all floating number, so conversion to wei will not fail anymore

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean.js#788]
**Describe the bug**
Sometimes, we get from the market floating numbers with too many decimals, and ToWei fails.

**Screenshots**
[Screenshot](https://ibb.co/88wGvT9)

**Expected behavior**
We should fix the precision, so conversion to Wei always succeeds

**Comment by AnaLoznianu** [comment]
Closing this issue as we have a major ocean.js refactor in pipe that will fix this.
