### ISSUE TITLE
Check tests for old use cases and inconsistencies

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/ocean.js#836]
It seems that we have old use cases that are no longer accurate and are misleading to users (and even the team).
One example is this , the market never sells the datatokens. https://github.com/oceanprotocol/ocean.js/blob/727a55046c44c1841360f6aa2a4f94befe157860/test/integration/Marketplaceflow.test.ts#L359

We need to check them

**Comment by kremalicious** [comment]
Will be made obsolete by new ocean.js which also start fresh with its tests
