### ISSUE TITLE
marketplace-quickstart minor errors

### ISSUE THREAD

**Issue by DMats** [oceanprotocol/ocean.js#884]
- [ ] Minor error in Step 12:

  > At the end of the `init() { ... }` function (after `console.log("bobTransaction", bobTransaction)`) add the following code:

  But at this point, `console.log("bobTransaction", bobTransaction)` doesn't exist in marketplace.js

- [ ] Typo in step 13 - "Oceon.js"

**Comment by kremalicious** [comment]
If anybody wants to do those changes now, go for it. But new ocean.js will also have new docs
