### ISSUE TITLE
createComputeService() passing "0" as timeout value will be "3600" instead of  "0"

### ISSUE THREAD

**Issue by krisliew** [oceanprotocol/ocean.js#918]
Same issue as in https://github.com/oceanprotocol/market/issues/733 

https://github.com/oceanprotocol/ocean.js/blob/666da8156fda8a3201b5b4cd600105017f65b275/src/ocean/Compute.ts#L339-L349

**Comment by AnaLoznianu** [comment]
Closing this as the "Forever" option as default doesn't make sense for C2D services
