### ISSUE TITLE
isConsumable check if `isRetired: true`

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/ocean.js#928]
The implementation of this check should be similar to https://github.com/oceanprotocol/ocean.js/issues/759. The function should check if the asset is consumable by:

- check if `isRetired: true` (it exists & true -> asset is not consumable)

Return should be a interface, containing a status and a status_message: Eg
0, All good
1, Asset is disabled

**Comment by kremalicious** [comment]
New ocean.js will be only a mirror of contract methods so this here is then obsolete
